name: CI Image Tests

on:
  push:
    branches:
      - test
      
  pull_request:
    branches:
      - test

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      # 拽 砖 拽 -repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 转拽转 Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Cache -pip  住 
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('app/requirements.txt') }}

      # 转拽转 dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest flake8

      # 专爪转 Lint
      - name: Run lint
        run: flake8 app/

      # 专爪转 Unit Tests 注 pytest
      - name: Run tests
        run: pytest app/tests --maxfail=1 --disable-warnings -q

      - name: All tests passed
        if: ${{ success() }}
        run: echo " All lint and pytest tests passed successfully!"
